#!/bin/bash
expose-fs /root --quiet --port=$PORT_8441 &

wait_for_fs () {
  if ! curl -fs localhost:$PORT_8441 > /dev/null; then
    sleep 0.2
    wait_for_fs
  fi
}

wait_for_fs

if [ -d /workshop ]; then
  rsync -r --ignore-existing /workshop/ /root
  
  if [ -f /workshop/welcome.txt ]; then
    cat /workshop/welcome.txt | format --host "$HOST" --container-id "$CONTAINER_ID" --port "$PORT" > /root/welcome.txt
    cat /root/welcome.txt
  fi
fi

/bin/bash --rcfile /root/.bashrc